//! Build script for niri-lua that generates EmmyLua type definitions.
//!
//! This script generates `types/api.lua` with EmmyLua annotations for LSP support.
//! The API schema is included from `src/api_data.rs` which is shared with the main crate.

// Allow private_interfaces warning because api_data.rs uses `pub const` for the main crate,
// but build.rs defines its own private schema types (which is fine for a build script).
#![allow(private_interfaces)]

use std::io::Write;
use std::path::Path;
use std::{env, fs};

// ============================================================================
// Schema Type Definitions (mirrors lua_api_schema.rs without `pub`)
// ============================================================================

/// Complete schema for the niri Lua API.
#[derive(Debug, Clone)]
struct LuaApiSchema {
    modules: &'static [ModuleSchema],
    types: &'static [TypeSchema],
    aliases: &'static [AliasSchema],
}

/// Schema for a Lua module/namespace.
#[derive(Debug, Clone)]
struct ModuleSchema {
    path: &'static str,
    description: &'static str,
    functions: &'static [FunctionSchema],
    fields: &'static [FieldSchema],
}

/// Schema for a function or method.
#[derive(Debug, Clone)]
struct FunctionSchema {
    name: &'static str,
    description: &'static str,
    is_method: bool,
    params: &'static [ParamSchema],
    returns: &'static [ReturnSchema],
}

/// Schema for a function parameter.
#[derive(Debug, Clone)]
struct ParamSchema {
    name: &'static str,
    ty: &'static str,
    description: &'static str,
    optional: bool,
}

/// Schema for a function return value.
#[derive(Debug, Clone)]
struct ReturnSchema {
    ty: &'static str,
    description: &'static str,
}

/// Schema for a field (module field or type field).
#[derive(Debug, Clone)]
struct FieldSchema {
    name: &'static str,
    ty: &'static str,
    description: &'static str,
}

/// Schema for a UserData type (class).
#[derive(Debug, Clone)]
struct TypeSchema {
    name: &'static str,
    description: &'static str,
    fields: &'static [FieldSchema],
    methods: &'static [FunctionSchema],
}

/// Schema for a type alias.
#[derive(Debug, Clone)]
struct AliasSchema {
    name: &'static str,
    ty: &'static str,
    description: &'static str,
}

// Include the shared API data (defines NIRI_LUA_API and all module constants)
include!("src/api_data.rs");

// ============================================================================
// EmmyLua Generation
// ============================================================================

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let types_dir = Path::new(&manifest_dir).join("types");

    // Create types directory if it doesn't exist
    fs::create_dir_all(&types_dir).unwrap();

    // Generate the EmmyLua file
    let output_path = types_dir.join("api.lua");
    generate_emmylua(&output_path);

    // Tell Cargo to rerun if relevant files change
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/api_data.rs");
}

fn generate_emmylua(output_path: &Path) {
    let mut output = String::new();

    // Header
    output.push_str("---@meta\n");
    output.push_str("-- THIS FILE IS AUTO-GENERATED BY build.rs - DO NOT EDIT\n");
    output.push_str("-- Regenerate by running: cargo build -p niri-lua\n");
    output.push_str("--\n");
    output.push_str("-- Niri Lua API Type Definitions\n");
    output.push_str("-- For use with EmmyLua-compatible LSP servers\n\n");

    // Generate type aliases from schema
    generate_aliases(&mut output);

    // Generate config classes (these are not in the schema yet)
    generate_config_classes(&mut output);

    // Generate UserData types from schema
    generate_types(&mut output);

    // Generate modules from schema
    generate_modules(&mut output);

    // Write the output file
    let mut file = fs::File::create(output_path).unwrap();
    file.write_all(output.as_bytes()).unwrap();
}

/// Generate type aliases from NIRI_LUA_API.aliases
fn generate_aliases(output: &mut String) {
    output.push_str(
        "-- ============================================================================\n",
    );
    output.push_str("-- Type Aliases\n");
    output.push_str(
        "-- ============================================================================\n\n",
    );

    for alias in NIRI_LUA_API.aliases {
        // Description
        output.push_str(&format!("---{}\n", alias.description));
        // Alias definition
        output.push_str(&format!("---@alias {} {}\n\n", alias.name, alias.ty));
    }
}

/// Generate config classes (not yet in schema - kept as hardcoded for now)
fn generate_config_classes(output: &mut String) {
    // Input Configuration Types
    output.push_str(
        "-- ============================================================================\n",
    );
    output.push_str("-- Input Configuration Types\n");
    output.push_str(
        "-- ============================================================================\n\n",
    );

    output.push_str("---XKB keyboard layout configuration\n");
    output.push_str("---@class XkbConfig\n");
    output.push_str("---@field rules string? XKB rules file\n");
    output.push_str("---@field model string? Keyboard model\n");
    output.push_str("---@field layout string? Keyboard layout (e.g., \"us\", \"de\", \"us,ru\")\n");
    output.push_str("---@field variant string? Layout variant (e.g., \"dvorak\", \"colemak\")\n");
    output.push_str(
        "---@field options string? XKB options (e.g., \"ctrl:nocaps\", \"compose:ralt\")\n",
    );
    output.push_str("---@field file string? Path to custom XKB file\n\n");

    output.push_str("---Keyboard configuration\n");
    output.push_str("---@class KeyboardConfig\n");
    output.push_str("---@field xkb XkbConfig? XKB layout configuration\n");
    output.push_str("---@field repeat_delay integer? Key repeat delay in milliseconds\n");
    output.push_str("---@field repeat_rate integer? Key repeat rate in characters per second\n");
    output.push_str(
        "---@field track_layout \"global\"|\"window\"? Track layout per-window or globally\n",
    );
    output.push_str("---@field numlock boolean? Enable NumLock on startup\n\n");

    output.push_str("---Touchpad configuration\n");
    output.push_str("---@class TouchpadConfig\n");
    output.push_str("---@field off boolean? Disable touchpad\n");
    output.push_str("---@field tap boolean? Enable tap-to-click\n");
    output.push_str("---@field dwt boolean? Disable while typing\n");
    output.push_str("---@field dwtp boolean? Disable while trackpointing\n");
    output.push_str("---@field drag boolean? Enable tap-and-drag\n");
    output.push_str("---@field drag_lock boolean? Enable drag lock\n");
    output.push_str("---@field natural_scroll boolean? Enable natural (inverted) scrolling\n");
    output.push_str("---@field click_method ClickMethod? Click detection method\n");
    output.push_str("---@field accel_speed number? Acceleration speed (-1.0 to 1.0)\n");
    output.push_str("---@field accel_profile AccelProfile? Acceleration profile\n");
    output.push_str("---@field scroll_method ScrollMethod? Scroll method\n");
    output.push_str("---@field scroll_button integer? Button for on-button-press scrolling\n");
    output.push_str("---@field scroll_button_lock boolean? Lock scroll button\n");
    output.push_str("---@field tap_button_map TapButtonMap? Tap button mapping\n");
    output.push_str("---@field left_handed boolean? Left-handed mode\n");
    output.push_str(
        "---@field disabled_on_external_mouse boolean? Disable when external mouse connected\n",
    );
    output.push_str("---@field middle_emulation boolean? Emulate middle button\n");
    output.push_str("---@field scroll_factor number? Scroll speed multiplier\n\n");

    output.push_str("---Mouse configuration\n");
    output.push_str("---@class MouseConfig\n");
    output.push_str("---@field off boolean? Disable mouse\n");
    output.push_str("---@field natural_scroll boolean? Enable natural scrolling\n");
    output.push_str("---@field accel_speed number? Acceleration speed (-1.0 to 1.0)\n");
    output.push_str("---@field accel_profile AccelProfile? Acceleration profile\n");
    output.push_str("---@field scroll_method ScrollMethod? Scroll method\n");
    output.push_str("---@field scroll_button integer? Button for on-button-press scrolling\n");
    output.push_str("---@field scroll_button_lock boolean? Lock scroll button\n");
    output.push_str("---@field left_handed boolean? Left-handed mode\n");
    output.push_str("---@field middle_emulation boolean? Emulate middle button\n");
    output.push_str("---@field scroll_factor number? Scroll speed multiplier\n\n");

    output.push_str("---Trackpoint configuration\n");
    output.push_str("---@class TrackpointConfig\n");
    output.push_str("---@field off boolean? Disable trackpoint\n");
    output.push_str("---@field natural_scroll boolean? Enable natural scrolling\n");
    output.push_str("---@field accel_speed number? Acceleration speed (-1.0 to 1.0)\n");
    output.push_str("---@field accel_profile AccelProfile? Acceleration profile\n");
    output.push_str("---@field scroll_method ScrollMethod? Scroll method\n");
    output.push_str("---@field scroll_button integer? Button for scrolling\n");
    output.push_str("---@field scroll_button_lock boolean? Lock scroll button\n");
    output.push_str("---@field left_handed boolean? Left-handed mode\n");
    output.push_str("---@field middle_emulation boolean? Emulate middle button\n\n");

    output.push_str("---Touch screen configuration\n");
    output.push_str("---@class TouchConfig\n");
    output.push_str("---@field off boolean? Disable touch\n");
    output.push_str("---@field map_to_output string? Map touch to specific output\n");
    output.push_str("---@field natural_scroll boolean? Enable natural scrolling for gestures\n\n");

    output.push_str("---Tablet configuration\n");
    output.push_str("---@class TabletConfig\n");
    output.push_str("---@field off boolean? Disable tablet\n");
    output.push_str("---@field map_to_output string? Map tablet to specific output\n");
    output.push_str("---@field left_handed boolean? Left-handed mode\n\n");

    output.push_str("---Focus follows mouse configuration\n");
    output.push_str("---@class FocusFollowsMouse\n");
    output.push_str(
        "---@field max_scroll_amount string? Maximum scroll amount (e.g., \"0%\", \"10%\")\n\n",
    );

    output.push_str("---Input configuration section\n");
    output.push_str("---@class InputConfig\n");
    output.push_str("---@field keyboard KeyboardConfig? Keyboard settings\n");
    output.push_str("---@field touchpad TouchpadConfig? Touchpad settings\n");
    output.push_str("---@field mouse MouseConfig? Mouse settings\n");
    output.push_str("---@field trackpoint TrackpointConfig? Trackpoint settings\n");
    output.push_str("---@field tablet TabletConfig? Graphics tablet settings\n");
    output.push_str("---@field touch TouchConfig? Touch screen settings\n");
    output.push_str(
        "---@field disable_power_key_handling boolean? Disable compositor power key handling\n",
    );
    output.push_str("---@field warp_mouse_to_focus boolean? Warp mouse to focused window\n");
    output.push_str(
        "---@field focus_follows_mouse FocusFollowsMouse|boolean? Focus follows mouse settings\n",
    );
    output.push_str("---@field workspace_auto_back_and_forth boolean? Auto switch back to previous workspace\n\n");

    // Layout Configuration Types
    output.push_str(
        "-- ============================================================================\n",
    );
    output.push_str("-- Layout Configuration Types\n");
    output.push_str(
        "-- ============================================================================\n\n",
    );

    output.push_str("---Focus ring configuration\n");
    output.push_str("---@class FocusRingConfig\n");
    output.push_str("---@field off boolean? Disable focus ring\n");
    output.push_str("---@field width integer? Ring width in pixels\n");
    output.push_str("---@field active_color Color? Color when focused\n");
    output.push_str("---@field inactive_color Color? Color when unfocused\n");
    output.push_str("---@field urgent_color Color? Color for urgent windows\n\n");

    output.push_str("---Border configuration\n");
    output.push_str("---@class BorderConfig\n");
    output.push_str("---@field off boolean? Disable border\n");
    output.push_str("---@field width integer? Border width in pixels\n");
    output.push_str("---@field active_color Color? Color when focused\n");
    output.push_str("---@field inactive_color Color? Color when unfocused\n");
    output.push_str("---@field urgent_color Color? Color for urgent windows\n\n");

    output.push_str("---Shadow offset\n");
    output.push_str("---@class ShadowOffset\n");
    output.push_str("---@field x number X offset\n");
    output.push_str("---@field y number Y offset\n\n");

    output.push_str("---Shadow configuration\n");
    output.push_str("---@class ShadowConfig\n");
    output.push_str("---@field on boolean? Enable shadow (default true)\n");
    output.push_str("---@field softness integer? Shadow blur softness\n");
    output.push_str("---@field spread integer? Shadow spread\n");
    output.push_str("---@field offset ShadowOffset? Shadow offset { x, y }\n");
    output.push_str("---@field color Color? Shadow color\n");
    output.push_str("---@field active_color Color? Shadow color when focused\n");
    output.push_str("---@field inactive_color Color? Shadow color when unfocused\n\n");

    output.push_str("---Column width preset (use one of these)\n");
    output.push_str("---@class ColumnWidthPreset\n");
    output.push_str("---@field proportion number? Proportion of workspace (0.0-1.0)\n");
    output.push_str("---@field fixed integer? Fixed pixel width\n\n");

    output.push_str("---Struts (reserved space) configuration\n");
    output.push_str("---@class StrutsConfig\n");
    output.push_str("---@field left integer? Left strut in pixels\n");
    output.push_str("---@field right integer? Right strut in pixels\n");
    output.push_str("---@field top integer? Top strut in pixels\n");
    output.push_str("---@field bottom integer? Bottom strut in pixels\n\n");

    output.push_str("---Layout configuration section\n");
    output.push_str("---@class LayoutConfig\n");
    output.push_str("---@field focus_ring FocusRingConfig? Focus ring settings\n");
    output.push_str("---@field border BorderConfig? Border settings\n");
    output.push_str("---@field shadow ShadowConfig? Shadow settings\n");
    output.push_str(
        "---@field preset_column_widths ColumnWidthPreset[]? Preset column widths to cycle\n",
    );
    output.push_str(
        "---@field default_column_width ColumnWidthPreset? Default width for new columns\n",
    );
    output.push_str(
        "---@field preset_window_heights ColumnWidthPreset[]? Preset window heights to cycle\n",
    );
    output.push_str(
        "---@field center_focused_column CenterFocusedColumn? When to center focused column\n",
    );
    output.push_str("---@field always_center_single_column boolean? Always center single column\n");
    output.push_str(
        "---@field empty_workspace_above_first boolean? Keep empty workspace above first\n",
    );
    output
        .push_str("---@field default_column_display ColumnDisplay? Default column display mode\n");
    output.push_str("---@field gaps integer? Gap between windows in pixels\n");
    output.push_str("---@field struts StrutsConfig? Reserved screen edge space\n");
    output.push_str("---@field background_color Color? Workspace background color\n\n");

    // Other Configuration Types
    output.push_str(
        "-- ============================================================================\n",
    );
    output.push_str("-- Other Configuration Types\n");
    output.push_str(
        "-- ============================================================================\n\n",
    );

    output.push_str("---Cursor configuration\n");
    output.push_str("---@class CursorConfig\n");
    output.push_str("---@field xcursor_theme string? Cursor theme name\n");
    output.push_str("---@field xcursor_size integer? Cursor size in pixels\n");
    output.push_str("---@field hide_when_typing boolean? Hide cursor while typing\n");
    output.push_str(
        "---@field hide_after_inactive_ms integer? Hide cursor after inactivity (ms)\n\n",
    );

    output.push_str("---Hot corners configuration\n");
    output.push_str("---@class HotCornersConfig\n");
    output.push_str("---@field off boolean? Disable hot corners\n");
    output.push_str("---@field top_left boolean? Enable top-left corner\n");
    output.push_str("---@field top_right boolean? Enable top-right corner\n");
    output.push_str("---@field bottom_left boolean? Enable bottom-left corner\n");
    output.push_str("---@field bottom_right boolean? Enable bottom-right corner\n\n");

    output.push_str("---Gestures configuration\n");
    output.push_str("---@class GesturesConfig\n");
    output.push_str("---@field hot_corners HotCornersConfig? Hot corners settings\n\n");

    output.push_str("---Recent windows highlight configuration\n");
    output.push_str("---@class RecentWindowsHighlight\n");
    output.push_str("---@field active_color Color? Active window highlight color\n");
    output.push_str("---@field urgent_color Color? Urgent window highlight color\n");
    output.push_str("---@field padding integer? Highlight padding\n");
    output.push_str("---@field corner_radius number? Highlight corner radius\n\n");

    output.push_str("---Recent windows preview configuration\n");
    output.push_str("---@class RecentWindowsPreviews\n");
    output.push_str("---@field max_height integer? Maximum preview height\n");
    output.push_str("---@field max_scale number? Maximum preview scale\n\n");

    output.push_str("---Recent windows (MRU) configuration\n");
    output.push_str("---@class RecentWindowsConfig\n");
    output.push_str("---@field off boolean? Disable recent windows UI\n");
    output.push_str("---@field open_delay_ms integer? Delay before showing UI\n");
    output.push_str("---@field highlight RecentWindowsHighlight? Highlight settings\n");
    output.push_str("---@field previews RecentWindowsPreviews? Preview settings\n\n");

    output.push_str("---Overview configuration\n");
    output.push_str("---@class OverviewConfig\n");
    output.push_str("---@field zoom number? Overview zoom level (0.0-1.0)\n");
    output.push_str("---@field backdrop_color Color? Backdrop color with alpha\n");
    output
        .push_str("---@field workspace_shadow ShadowConfig? Shadow for workspaces in overview\n\n");

    output.push_str("---Animations configuration\n");
    output.push_str("---@class AnimationsConfig\n");
    output.push_str("---@field off boolean? Disable all animations\n");
    output.push_str("---@field slowdown number? Animation slowdown factor (1.0 = normal)\n\n");

    output.push_str("---Clipboard configuration\n");
    output.push_str("---@class ClipboardConfig\n");
    output.push_str(
        "---@field disable_primary boolean? Disable primary selection (middle-click paste)\n\n",
    );

    output.push_str("---Hotkey overlay configuration\n");
    output.push_str("---@class HotkeyOverlayConfig\n");
    output.push_str("---@field skip_at_startup boolean? Don't show overlay on startup\n\n");

    output.push_str("---Config notification configuration\n");
    output.push_str("---@class ConfigNotificationConfig\n");
    output.push_str("---@field disable_failed boolean? Disable failed config notification\n\n");

    output.push_str("---Debug configuration\n");
    output.push_str("---@class DebugConfig\n");
    output.push_str("---@field disable_direct_scanout boolean? Disable direct scanout\n\n");

    output.push_str("---Xwayland satellite configuration\n");
    output.push_str("---@class XwaylandSatelliteConfig\n");
    output.push_str("---@field off boolean? Disable Xwayland satellite\n\n");
}

/// Generate UserData types from NIRI_LUA_API.types
fn generate_types(output: &mut String) {
    output.push_str(
        "-- ============================================================================\n",
    );
    output.push_str("-- UserData Types\n");
    output.push_str(
        "-- ============================================================================\n\n",
    );

    for ty in NIRI_LUA_API.types {
        // Class description
        output.push_str(&format!("---{}\n", ty.description));
        output.push_str(&format!("---@class {}\n", ty.name));

        // Fields
        for field in ty.fields {
            output.push_str(&format!(
                "---@field {} {} {}\n",
                field.name, field.ty, field.description
            ));
        }

        // Local variable declaration (for methods to attach to)
        output.push_str(&format!("local {} = {{}}\n\n", ty.name));

        // Methods
        for method in ty.methods {
            generate_function(output, ty.name, method, true);
        }
    }
}

/// Generate modules from NIRI_LUA_API.modules
fn generate_modules(output: &mut String) {
    output.push_str(
        "-- ============================================================================\n",
    );
    output.push_str("-- Modules\n");
    output.push_str(
        "-- ============================================================================\n\n",
    );

    for module in NIRI_LUA_API.modules {
        // Module class definition
        // Use underscore format for class names to match field type references
        let class_name = module.path.replace('.', "_");
        output.push_str(&format!("---{}\n", module.description));
        output.push_str(&format!("---@class {}\n", class_name));

        // Module fields (sub-modules)
        for field in module.fields {
            output.push_str(&format!(
                "---@field {} {} {}\n",
                field.name, field.ty, field.description
            ));
        }

        // Module variable
        let var_name = module.path.replace('.', "_");
        output.push_str(&format!("{} = {{}}\n\n", var_name));

        // Functions
        for func in module.functions {
            generate_function(output, &var_name, func, false);
        }
    }
}

/// Generate a function or method
fn generate_function(output: &mut String, parent: &str, func: &FunctionSchema, is_method: bool) {
    // Description
    output.push_str(&format!("---{}\n", func.description));

    // Parameters
    for param in func.params {
        let optional_marker = if param.optional { "?" } else { "" };
        output.push_str(&format!(
            "---@param {}{} {} {}\n",
            param.name, optional_marker, param.ty, param.description
        ));
    }

    // Returns
    for ret in func.returns {
        if ret.description.is_empty() {
            output.push_str(&format!("---@return {}\n", ret.ty));
        } else {
            output.push_str(&format!("---@return {} # {}\n", ret.ty, ret.description));
        }
    }

    // Function signature
    let params: Vec<&str> = func.params.iter().map(|p| p.name).collect();
    let params_str = params.join(", ");

    let separator = if is_method || func.is_method {
        ":"
    } else {
        "."
    };
    output.push_str(&format!(
        "function {}{}{}({}) end\n\n",
        parent, separator, func.name, params_str
    ));
}
