---@meta
-- THIS FILE IS AUTO-GENERATED BY build.rs - DO NOT EDIT
-- Regenerate by running: cargo build -p niri-lua
--
-- Niri Lua API Type Definitions
-- For use with EmmyLua-compatible LSP servers

-- ============================================================================
-- Type Aliases
-- ============================================================================

---Window information table
---@alias Window { id: integer, title: string?, app_id: string?, workspace_id: integer?, is_focused: boolean, is_floating: boolean }

---Workspace information table
---@alias Workspace { id: integer, idx: integer, name: string?, output: string?, is_active: boolean, is_focused: boolean, active_window_id: integer? }

---Output/monitor information table with position, scale, and transform
---@alias Output { name: string, make: string?, model: string?, serial: string?, physical_size: { width: integer, height: integer }?, current_mode: { width: integer, height: integer, refresh: integer }?, vrr_supported: boolean, vrr_enabled: boolean, x: integer?, y: integer?, scale: number?, logical_width: integer?, logical_height: integer?, transform: integer?, refresh_hz: number? }

---Size change value: integer for absolute, '+N'/'-N' for relative, 'N%' for percentage
---@alias SizeChange integer|string

---Position change value: integer for absolute, '+N'/'-N' for relative
---@alias PositionChange integer|string

---Layout switch target: 'next', 'prev', or layout name
---@alias LayoutSwitchTarget "next"|"prev"|string

---Workspace reference: index, name, or table with id/name/index
---@alias WorkspaceReference integer|string|{ id: integer }|{ name: string }|{ index: integer }

---Event handler identifier returned by niri.events:on() or :once()
---@alias EventHandlerId integer

---Event specification: single event name or array of event names
---@alias EventSpec string|string[]

---Map of event names to handler IDs, returned when registering multiple events
---@alias HandlerIdMap table<string, EventHandlerId>

---Keybinding entry with key combination, action, and optional parameters
---@alias BindEntry { key: string, action: string, args: any[]?, cooldown_ms: integer?, allow_when_locked: boolean? }

---Output/monitor configuration
---@alias OutputConfig { name: string, mode: string?, scale: number?, position: { x: integer, y: integer }?, transform: string?, vrr: boolean? }

---Window rule configuration with match criteria and properties
---@alias WindowRuleConfig { match: { app_id: string?, title: string?, is_floating: boolean?, at_startup: boolean? }?, default_column_width: table?, open_floating: boolean?, open_fullscreen: boolean?, open_maximized: boolean?, block_out_from: string?, opacity: number?, draw_border_with_background: boolean?, geometry_corner_radius: table?, clip_to_geometry: boolean?, focus_ring: table?, border: table? }

---Cursor position with coordinates and output name
---@alias CursorPosition { x: number, y: number, output: string }

---Reserved (exclusive) space on each edge from layer-shell surfaces
---@alias ReservedSpace { top: integer, bottom: integer, left: integer, right: integer }

---Current compositor focus mode
---@alias FocusMode "normal"|"overview"|"layer_shell"|"locked"

---Keyboard layout names and current active index
---@alias KeyboardLayouts { names: string[], current_idx: integer }

---Options for niri.fs.find() function. path: starting directory (default cwd), upward: search toward root, stop: stop directory for upward search, type: filter by file/directory, limit: max results
---@alias FsFindOpts { path: string?, upward: boolean?, stop: string?, type: "file"|"directory"?, limit: integer? }

-- ============================================================================
-- Input Configuration Types
-- ============================================================================

---XKB keyboard layout configuration
---@class XkbConfig
---@field rules string? XKB rules file
---@field model string? Keyboard model
---@field layout string? Keyboard layout (e.g., "us", "de", "us,ru")
---@field variant string? Layout variant (e.g., "dvorak", "colemak")
---@field options string? XKB options (e.g., "ctrl:nocaps", "compose:ralt")
---@field file string? Path to custom XKB file

---Keyboard configuration
---@class KeyboardConfig
---@field xkb XkbConfig? XKB layout configuration
---@field repeat_delay integer? Key repeat delay in milliseconds
---@field repeat_rate integer? Key repeat rate in characters per second
---@field track_layout "global"|"window"? Track layout per-window or globally
---@field numlock boolean? Enable NumLock on startup

---Touchpad configuration
---@class TouchpadConfig
---@field off boolean? Disable touchpad
---@field tap boolean? Enable tap-to-click
---@field dwt boolean? Disable while typing
---@field dwtp boolean? Disable while trackpointing
---@field drag boolean? Enable tap-and-drag
---@field drag_lock boolean? Enable drag lock
---@field natural_scroll boolean? Enable natural (inverted) scrolling
---@field click_method ClickMethod? Click detection method
---@field accel_speed number? Acceleration speed (-1.0 to 1.0)
---@field accel_profile AccelProfile? Acceleration profile
---@field scroll_method ScrollMethod? Scroll method
---@field scroll_button integer? Button for on-button-press scrolling
---@field scroll_button_lock boolean? Lock scroll button
---@field tap_button_map TapButtonMap? Tap button mapping
---@field left_handed boolean? Left-handed mode
---@field disabled_on_external_mouse boolean? Disable when external mouse connected
---@field middle_emulation boolean? Emulate middle button
---@field scroll_factor number? Scroll speed multiplier

---Mouse configuration
---@class MouseConfig
---@field off boolean? Disable mouse
---@field natural_scroll boolean? Enable natural scrolling
---@field accel_speed number? Acceleration speed (-1.0 to 1.0)
---@field accel_profile AccelProfile? Acceleration profile
---@field scroll_method ScrollMethod? Scroll method
---@field scroll_button integer? Button for on-button-press scrolling
---@field scroll_button_lock boolean? Lock scroll button
---@field left_handed boolean? Left-handed mode
---@field middle_emulation boolean? Emulate middle button
---@field scroll_factor number? Scroll speed multiplier

---Trackpoint configuration
---@class TrackpointConfig
---@field off boolean? Disable trackpoint
---@field natural_scroll boolean? Enable natural scrolling
---@field accel_speed number? Acceleration speed (-1.0 to 1.0)
---@field accel_profile AccelProfile? Acceleration profile
---@field scroll_method ScrollMethod? Scroll method
---@field scroll_button integer? Button for scrolling
---@field scroll_button_lock boolean? Lock scroll button
---@field left_handed boolean? Left-handed mode
---@field middle_emulation boolean? Emulate middle button

---Touch screen configuration
---@class TouchConfig
---@field off boolean? Disable touch
---@field map_to_output string? Map touch to specific output
---@field natural_scroll boolean? Enable natural scrolling for gestures

---Tablet configuration
---@class TabletConfig
---@field off boolean? Disable tablet
---@field map_to_output string? Map tablet to specific output
---@field left_handed boolean? Left-handed mode

---Focus follows mouse configuration
---@class FocusFollowsMouse
---@field max_scroll_amount string? Maximum scroll amount (e.g., "0%", "10%")

---Input configuration section
---@class InputConfig
---@field keyboard KeyboardConfig? Keyboard settings
---@field touchpad TouchpadConfig? Touchpad settings
---@field mouse MouseConfig? Mouse settings
---@field trackpoint TrackpointConfig? Trackpoint settings
---@field tablet TabletConfig? Graphics tablet settings
---@field touch TouchConfig? Touch screen settings
---@field disable_power_key_handling boolean? Disable compositor power key handling
---@field warp_mouse_to_focus boolean? Warp mouse to focused window
---@field focus_follows_mouse FocusFollowsMouse|boolean? Focus follows mouse settings
---@field workspace_auto_back_and_forth boolean? Auto switch back to previous workspace

-- ============================================================================
-- Layout Configuration Types
-- ============================================================================

---Focus ring configuration
---@class FocusRingConfig
---@field off boolean? Disable focus ring
---@field width integer? Ring width in pixels
---@field active_color Color? Color when focused
---@field inactive_color Color? Color when unfocused
---@field urgent_color Color? Color for urgent windows

---Border configuration
---@class BorderConfig
---@field off boolean? Disable border
---@field width integer? Border width in pixels
---@field active_color Color? Color when focused
---@field inactive_color Color? Color when unfocused
---@field urgent_color Color? Color for urgent windows

---Shadow offset
---@class ShadowOffset
---@field x number X offset
---@field y number Y offset

---Shadow configuration
---@class ShadowConfig
---@field on boolean? Enable shadow (default true)
---@field softness integer? Shadow blur softness
---@field spread integer? Shadow spread
---@field offset ShadowOffset? Shadow offset { x, y }
---@field color Color? Shadow color
---@field active_color Color? Shadow color when focused
---@field inactive_color Color? Shadow color when unfocused

---Column width preset (use one of these)
---@class ColumnWidthPreset
---@field proportion number? Proportion of workspace (0.0-1.0)
---@field fixed integer? Fixed pixel width

---Struts (reserved space) configuration
---@class StrutsConfig
---@field left integer? Left strut in pixels
---@field right integer? Right strut in pixels
---@field top integer? Top strut in pixels
---@field bottom integer? Bottom strut in pixels

---Layout configuration section
---@class LayoutConfig
---@field focus_ring FocusRingConfig? Focus ring settings
---@field border BorderConfig? Border settings
---@field shadow ShadowConfig? Shadow settings
---@field preset_column_widths ColumnWidthPreset[]? Preset column widths to cycle
---@field default_column_width ColumnWidthPreset? Default width for new columns
---@field preset_window_heights ColumnWidthPreset[]? Preset window heights to cycle
---@field center_focused_column CenterFocusedColumn? When to center focused column
---@field always_center_single_column boolean? Always center single column
---@field empty_workspace_above_first boolean? Keep empty workspace above first
---@field default_column_display ColumnDisplay? Default column display mode
---@field gaps integer? Gap between windows in pixels
---@field struts StrutsConfig? Reserved screen edge space
---@field background_color Color? Workspace background color

-- ============================================================================
-- Other Configuration Types
-- ============================================================================

---Cursor configuration
---@class CursorConfig
---@field xcursor_theme string? Cursor theme name
---@field xcursor_size integer? Cursor size in pixels
---@field hide_when_typing boolean? Hide cursor while typing
---@field hide_after_inactive_ms integer? Hide cursor after inactivity (ms)

---Hot corners configuration
---@class HotCornersConfig
---@field off boolean? Disable hot corners
---@field top_left boolean? Enable top-left corner
---@field top_right boolean? Enable top-right corner
---@field bottom_left boolean? Enable bottom-left corner
---@field bottom_right boolean? Enable bottom-right corner

---Gestures configuration
---@class GesturesConfig
---@field hot_corners HotCornersConfig? Hot corners settings

---Recent windows highlight configuration
---@class RecentWindowsHighlight
---@field active_color Color? Active window highlight color
---@field urgent_color Color? Urgent window highlight color
---@field padding integer? Highlight padding
---@field corner_radius number? Highlight corner radius

---Recent windows preview configuration
---@class RecentWindowsPreviews
---@field max_height integer? Maximum preview height
---@field max_scale number? Maximum preview scale

---Recent windows (MRU) configuration
---@class RecentWindowsConfig
---@field off boolean? Disable recent windows UI
---@field open_delay_ms integer? Delay before showing UI
---@field highlight RecentWindowsHighlight? Highlight settings
---@field previews RecentWindowsPreviews? Preview settings

---Overview configuration
---@class OverviewConfig
---@field zoom number? Overview zoom level (0.0-1.0)
---@field backdrop_color Color? Backdrop color with alpha
---@field workspace_shadow ShadowConfig? Shadow for workspaces in overview

---Animations configuration
---@class AnimationsConfig
---@field off boolean? Disable all animations
---@field slowdown number? Animation slowdown factor (1.0 = normal)

---Clipboard configuration
---@class ClipboardConfig
---@field disable_primary boolean? Disable primary selection (middle-click paste)

---Hotkey overlay configuration
---@class HotkeyOverlayConfig
---@field skip_at_startup boolean? Don't show overlay on startup

---Config notification configuration
---@class ConfigNotificationConfig
---@field disable_failed boolean? Disable failed config notification

---Debug configuration
---@class DebugConfig
---@field disable_direct_scanout boolean? Disable direct scanout

---Xwayland satellite configuration
---@class XwaylandSatelliteConfig
---@field off boolean? Disable Xwayland satellite

-- ============================================================================
-- UserData Types
-- ============================================================================

---A timer for scheduling callbacks
---@class Timer
---@field id integer Unique timer identifier
local Timer = {}

---Start the timer with a delay and optional repeat interval
---@param delay_ms integer Delay in milliseconds before first callback
---@param repeat_ms? integer Repeat interval in milliseconds (0 for one-shot)
---@param callback fun() Callback function
---@return Timer # Self for chaining
function Timer:start(delay_ms, repeat_ms, callback) end

---Stop the timer without closing it
---@return Timer # Self for chaining
function Timer:stop() end

---Stop and close the timer, releasing resources
function Timer:close() end

---Check if the timer is currently active
---@return boolean # True if timer is active
function Timer:is_active() end

---Animation configuration
---@class Animation
---@field name string Animation name
---@field duration_ms integer Duration in milliseconds
---@field curve string Easing curve
local Animation = {}

---Get the animation name
---@return string
function Animation:get_name() end

---Get the duration in milliseconds
---@return integer
function Animation:get_duration() end

---Get the easing curve
---@return string
function Animation:get_curve() end

---Create a copy with different duration
---@param ms integer Duration in milliseconds
---@return Animation # New animation with updated duration
function Animation:with_duration(ms) end

---Create a copy with different easing curve
---@param curve string Easing curve name
---@return Animation # New animation with updated curve
function Animation:with_curve(curve) end

---Window filter for matching windows
---@class Filter
local Filter = {}

---Check if a window matches this filter
---@param app_id string? Application ID
---@param title string? Window title
---@return boolean # True if window matches
function Filter:matches(app_id, title) end

---Get the app_id pattern
---@return string?
function Filter:get_app_id() end

---Get the title pattern
---@return string?
function Filter:get_title() end

---Window rule configuration
---@class WindowRule
local WindowRule = {}

---Check if a window matches this rule
---@param app_id string? Application ID
---@param title string? Window title
---@return boolean # True if window matches
function WindowRule:matches(app_id, title) end

---Get floating setting
---@return boolean?
function WindowRule:get_floating() end

---Get fullscreen setting
---@return boolean?
function WindowRule:get_fullscreen() end

---Get tile setting
---@return boolean?
function WindowRule:get_tile() end

---Create a copy with floating setting
---@param floating boolean Floating state
---@return WindowRule # New rule with updated setting
function WindowRule:with_floating(floating) end

---Create a copy with fullscreen setting
---@param fullscreen boolean Fullscreen state
---@return WindowRule # New rule with updated setting
function WindowRule:with_fullscreen(fullscreen) end

---Create a copy with tile setting
---@param tile boolean Tile state
---@return WindowRule # New rule with updated setting
function WindowRule:with_tile(tile) end

---Gesture configuration
---@class Gesture
local Gesture = {}

---Get the gesture type
---@return string
function Gesture:get_type() end

---Get the number of fingers
---@return integer
function Gesture:get_fingers() end

---Get the gesture direction
---@return string?
function Gesture:get_direction() end

---Get the bound action
---@return string?
function Gesture:get_action() end

---Create a copy with different direction
---@param direction string Gesture direction
---@return Gesture # New gesture with updated direction
function Gesture:with_direction(direction) end

---Create a copy with different action
---@param action string Action to bind
---@return Gesture # New gesture with updated action
function Gesture:with_action(action) end

---Collection proxy for CRUD operations on config arrays (binds, outputs, window_rules, etc.)
---@class ConfigCollection
local ConfigCollection = {}

---Get all items in the collection
---@return table[] # Array of all items
function ConfigCollection:list() end

---Get items matching criteria
---@param criteria table Match criteria (e.g., { key = 'Mod+T' })
---@return table[] # Matching items
function ConfigCollection:get(criteria) end

---Add one or more items to the collection
---@param items table|table[] Item or array of items to add
function ConfigCollection:add(items) end

---Replace the entire collection with new items
---@param items table[] New items to replace collection
function ConfigCollection:set(items) end

---Remove items matching criteria
---@param criteria table Match criteria for removal
---@return integer # Number of items removed
function ConfigCollection:remove(criteria) end

---Remove all items from the collection
function ConfigCollection:clear() end

---Proxy for config sections supporting direct table assignment and nested property access
---@class ConfigSectionProxy
local ConfigSectionProxy = {}

-- ============================================================================
-- Modules
-- ============================================================================

---Root niri namespace providing access to compositor functionality
---@class niri
---@field utils niri.utils Utility functions
---@field config niri.config Configuration API
---@field events niri.events Event system for subscribing to compositor events
---@field action niri.action Compositor actions
---@field state niri.state Runtime state queries
---@field loop niri.loop Event loop and timers
---@field keymap niri.keymap Keybinding configuration
---@field window niri.window Window rules configuration
---@field overview niri.overview Overview mode configuration
---@field screenshot niri.screenshot Screenshot configuration
---@field os niri.os Operating system utilities (hostname, getenv)
---@field fs niri.fs Filesystem utilities (readable, expand, which)
niri = {}

---Returns the niri version string
---@return string # niri version
function niri.version() end

---Print values to the niri log (info level)
---@param ... any Values to print
function niri.print(...) end

---Apply configuration from a Lua table
---@param config table Configuration table
function niri.apply_config(config) end

---Schedule a callback to run on the next event loop iteration. Useful for deferring work or avoiding reentrancy issues.
---@param callback function Function to execute on next iteration
function niri.schedule(callback) end

---Utility functions for logging and process spawning
---@class niri.utils
niri.utils = {}

---Log a message at info level
---@param ... any Values to log
function niri.utils.log(...) end

---Log a message at debug level
---@param ... any Values to log
function niri.utils.debug(...) end

---Log a message at warning level
---@param ... any Values to log
function niri.utils.warn(...) end

---Log a message at error level
---@param ... any Values to log
function niri.utils.error(...) end

---Spawn a command asynchronously
---@param command string[] Command and arguments
function niri.utils.spawn(command) end

---Configuration proxy for reading and modifying compositor settings
---@class niri.config
---@field input ConfigSectionProxy Input device configuration (keyboard, mouse, touchpad, etc.)
---@field layout ConfigSectionProxy Layout configuration (gaps, focus ring, border, shadow, etc.)
---@field cursor ConfigSectionProxy Cursor configuration (size, theme, hide when typing)
---@field gestures ConfigSectionProxy Gesture configuration (hot corners, touchpad gestures)
---@field recent_windows ConfigSectionProxy Recent windows (MRU) configuration
---@field overview ConfigSectionProxy Overview mode configuration (zoom, backdrop, shadows)
---@field animations ConfigSectionProxy Animation configuration (off, slowdown)
---@field clipboard ConfigSectionProxy Clipboard configuration
---@field hotkey_overlay ConfigSectionProxy Hotkey overlay configuration
---@field config_notification ConfigSectionProxy Config reload notification settings
---@field debug ConfigSectionProxy Debug configuration options
---@field xwayland_satellite ConfigSectionProxy Xwayland satellite configuration
---@field screenshot_path string Screenshot save path pattern
---@field prefer_no_csd boolean Prefer server-side decorations
---@field binds ConfigCollection Keybindings collection
---@field outputs ConfigCollection Output/monitor configurations
---@field workspaces ConfigCollection Named workspaces
---@field window_rules ConfigCollection Window rules
---@field layer_rules ConfigCollection Layer shell rules
---@field environment ConfigCollection Environment variables
niri.config = {}

---Apply all staged configuration changes to the compositor
function niri.config:apply() end

---Enable or disable automatic application of config changes
---@param enable boolean Whether to auto-apply changes
function niri.config:auto_apply(enable) end

---Returns the config API version
---@return string # Config API version
function niri.config.version() end

---Event system for subscribing to compositor events
---@class niri.events
niri.events = {}

---Subscribe to event(s) with a callback. Pass a single event name to get a handler ID, or an array of event names to get a table mapping event names to handler IDs.
---@param event_spec EventSpec Event name or array of event names (e.g., 'window:open' or {'window:open', 'window:close'})
---@param callback fun(event: table) Callback function receiving event data
---@return EventHandlerId|HandlerIdMap # Handler ID (single event) or table of handler IDs (multiple events)
function niri.events:on(event_spec, callback) end

---Subscribe to event(s) for a single occurrence. Handler is automatically removed after firing. Pass a single event name to get a handler ID, or an array of event names to get a table mapping event names to handler IDs.
---@param event_spec EventSpec Event name or array of event names
---@param callback fun(event: table) Callback function
---@return EventHandlerId|HandlerIdMap # Handler ID (single event) or table of handler IDs (multiple events)
function niri.events:once(event_spec, callback) end

---Unsubscribe from event(s). Pass (event_name, handler_id) to remove a single handler, or pass a HandlerIdMap table to remove multiple handlers at once.
---@param event_or_map string|HandlerIdMap Event name (with handler_id) or handler ID map from on()/once()
---@param handler_id? EventHandlerId Handler ID (only when first arg is event name)
---@return boolean|table<string, boolean> # True if handler removed (single) or table of results (multiple)
function niri.events:off(event_or_map, handler_id) end

---Emit a custom event (for testing or custom integrations)
---@param event_name string Event name
---@param data? table? Event data
function niri.events:emit(event_name, data) end

---Compositor actions for window management, navigation, and system control
---@class niri.action
niri.action = {}

---Quit the compositor
---@param skip_confirmation? boolean Skip confirmation dialog
function niri.action:quit(skip_confirmation) end

---Turn off all monitors
function niri.action:power_off_monitors() end

---Turn on all monitors
function niri.action:power_on_monitors() end

---Spawn a command (fire-and-forget).
---@param command string[] Command and arguments
function niri.action:spawn(command) end

---Spawn a command via shell (fire-and-forget).
---@param command string Shell command string
function niri.action:spawn_sh(command) end

---Trigger a screen transition animation
---@param delay? boolean Whether to delay the transition
function niri.action:do_screen_transition(delay) end

---Reload configuration from file
function niri.action:load_config_file() end

---Take a screenshot (interactive selection)
function niri.action:screenshot() end

---Screenshot the entire screen
function niri.action:screenshot_screen() end

---Screenshot the focused window
function niri.action:screenshot_window() end

---Close the focused window
function niri.action:close_window() end

---Toggle fullscreen on the focused window
function niri.action:fullscreen_window() end

---Toggle windowed fullscreen mode
function niri.action:toggle_windowed_fullscreen() end

---Focus a specific window by ID
---@param window_id integer Window ID
function niri.action:focus_window(window_id) end

---Focus the window at index within current column
---@param index integer 1-based window index
function niri.action:focus_window_in_column(index) end

---Focus the previously focused window
function niri.action:focus_window_previous() end

---Toggle keyboard shortcuts inhibit for focused window
function niri.action:toggle_keyboard_shortcuts_inhibit() end

---Focus the column to the left
function niri.action:focus_column_left() end

---Focus the column to the right
function niri.action:focus_column_right() end

---Focus the first column
function niri.action:focus_column_first() end

---Focus the last column
function niri.action:focus_column_last() end

---Focus column to the right, wrapping to first
function niri.action:focus_column_right_or_first() end

---Focus column to the left, wrapping to last
function niri.action:focus_column_left_or_last() end

---Focus column at specific index
---@param index integer 1-based column index
function niri.action:focus_column(index) end

---Focus the window below in the column
function niri.action:focus_window_down() end

---Focus the window above in the column
function niri.action:focus_window_up() end

---Focus window below or column left if at bottom
function niri.action:focus_window_down_or_column_left() end

---Focus window below or column right if at bottom
function niri.action:focus_window_down_or_column_right() end

---Focus window above or column left if at top
function niri.action:focus_window_up_or_column_left() end

---Focus window above or column right if at top
function niri.action:focus_window_up_or_column_right() end

---Focus window above or monitor above
function niri.action:focus_window_or_monitor_up() end

---Focus window below or monitor below
function niri.action:focus_window_or_monitor_down() end

---Focus column left or monitor left
function niri.action:focus_column_or_monitor_left() end

---Focus column right or monitor right
function niri.action:focus_column_or_monitor_right() end

---Move column to the left
function niri.action:move_column_left() end

---Move column to the right
function niri.action:move_column_right() end

---Move column to first position
function niri.action:move_column_to_first() end

---Move column to last position
function niri.action:move_column_to_last() end

---Move column left or to monitor left
function niri.action:move_column_left_or_to_monitor_left() end

---Move column right or to monitor right
function niri.action:move_column_right_or_to_monitor_right() end

---Move column to specific index
---@param index integer 1-based target index
function niri.action:move_column_to_index(index) end

---Move window down within column
function niri.action:move_window_down() end

---Move window up within column
function niri.action:move_window_up() end

---Move window down or to workspace below
function niri.action:move_window_down_or_to_workspace_down() end

---Move window up or to workspace above
function niri.action:move_window_up_or_to_workspace_up() end

---Consume window from left column or expel to left
function niri.action:consume_or_expel_window_left() end

---Consume window from right column or expel to right
function niri.action:consume_or_expel_window_right() end

---Consume adjacent window into current column
function niri.action:consume_window_into_column() end

---Expel focused window from column
function niri.action:expel_window_from_column() end

---Swap window with the one to the right
function niri.action:swap_window_right() end

---Swap window with the one to the left
function niri.action:swap_window_left() end

---Toggle tabbed display for column
function niri.action:toggle_column_tabbed_display() end

---Set column display mode
---@param mode "normal"|"tabbed" Display mode
function niri.action:set_column_display(mode) end

---Center the current column on screen
function niri.action:center_column() end

---Center the focused window on screen
function niri.action:center_window() end

---Center all visible columns
function niri.action:center_visible_columns() end

---Focus the workspace below
function niri.action:focus_workspace_down() end

---Focus the workspace above
function niri.action:focus_workspace_up() end

---Focus a specific workspace
---@param reference WorkspaceReference Workspace to focus
function niri.action:focus_workspace(reference) end

---Focus the previously active workspace
function niri.action:focus_workspace_previous() end

---Move window to workspace below
function niri.action:move_window_to_workspace_down() end

---Move window to workspace above
function niri.action:move_window_to_workspace_up() end

---Move window to specific workspace
---@param reference WorkspaceReference Target workspace
function niri.action:move_window_to_workspace(reference) end

---Move column to workspace below
function niri.action:move_column_to_workspace_down() end

---Move column to workspace above
function niri.action:move_column_to_workspace_up() end

---Move column to specific workspace
---@param reference WorkspaceReference Target workspace
function niri.action:move_column_to_workspace(reference) end

---Move current workspace down
function niri.action:move_workspace_down() end

---Move current workspace up
function niri.action:move_workspace_up() end

---Set the name of current workspace
---@param name string Workspace name
function niri.action:set_workspace_name(name) end

---Clear the name of current workspace
function niri.action:unset_workspace_name() end

---Focus monitor to the left
function niri.action:focus_monitor_left() end

---Focus monitor to the right
function niri.action:focus_monitor_right() end

---Focus monitor below
function niri.action:focus_monitor_down() end

---Focus monitor above
function niri.action:focus_monitor_up() end

---Focus previously active monitor
function niri.action:focus_monitor_previous() end

---Focus next monitor in order
function niri.action:focus_monitor_next() end

---Focus specific monitor by name
---@param name string Monitor name
function niri.action:focus_monitor(name) end

---Move window to monitor on the left
function niri.action:move_window_to_monitor_left() end

---Move window to monitor on the right
function niri.action:move_window_to_monitor_right() end

---Move window to monitor below
function niri.action:move_window_to_monitor_down() end

---Move window to monitor above
function niri.action:move_window_to_monitor_up() end

---Move window to previously active monitor
function niri.action:move_window_to_monitor_previous() end

---Move window to next monitor
function niri.action:move_window_to_monitor_next() end

---Move window to specific monitor
---@param name string Monitor name
function niri.action:move_window_to_monitor(name) end

---Move column to monitor on the left
function niri.action:move_column_to_monitor_left() end

---Move column to monitor on the right
function niri.action:move_column_to_monitor_right() end

---Move column to monitor below
function niri.action:move_column_to_monitor_down() end

---Move column to monitor above
function niri.action:move_column_to_monitor_up() end

---Move column to previously active monitor
function niri.action:move_column_to_monitor_previous() end

---Move column to next monitor
function niri.action:move_column_to_monitor_next() end

---Move column to specific monitor
---@param name string Monitor name
function niri.action:move_column_to_monitor(name) end

---Move workspace to monitor on the left
function niri.action:move_workspace_to_monitor_left() end

---Move workspace to monitor on the right
function niri.action:move_workspace_to_monitor_right() end

---Move workspace to monitor below
function niri.action:move_workspace_to_monitor_down() end

---Move workspace to monitor above
function niri.action:move_workspace_to_monitor_up() end

---Move workspace to previously active monitor
function niri.action:move_workspace_to_monitor_previous() end

---Move workspace to next monitor
function niri.action:move_workspace_to_monitor_next() end

---Move workspace to specific monitor
---@param name string Monitor name
function niri.action:move_workspace_to_monitor(name) end

---Set the window width
---@param change SizeChange Width change value
function niri.action:set_window_width(change) end

---Set the window height
---@param change SizeChange Height change value
function niri.action:set_window_height(change) end

---Reset window height to default
function niri.action:reset_window_height() end

---Switch to next preset column width
function niri.action:switch_preset_column_width() end

---Switch to previous preset column width
function niri.action:switch_preset_column_width_reverse() end

---Switch to next preset window width
function niri.action:switch_preset_window_width() end

---Switch to previous preset window width
function niri.action:switch_preset_window_width_reverse() end

---Switch to next preset window height
function niri.action:switch_preset_window_height() end

---Switch to previous preset window height
function niri.action:switch_preset_window_height_reverse() end

---Maximize column to fill workspace
function niri.action:maximize_column() end

---Maximize window to edges
function niri.action:maximize_window_to_edges() end

---Set column width
---@param change SizeChange Width change value
function niri.action:set_column_width(change) end

---Expand column to fill available width
function niri.action:expand_column_to_available_width() end

---Switch keyboard layout
---@param target LayoutSwitchTarget Layout to switch to
function niri.action:switch_layout(target) end

---Show the hotkey overlay
function niri.action:show_hotkey_overlay() end

---Toggle debug tint visualization
function niri.action:toggle_debug_tint() end

---Toggle opaque regions debug visualization
function niri.action:debug_toggle_opaque_regions() end

---Toggle damage debug visualization
function niri.action:debug_toggle_damage() end

---Toggle floating state of focused window
function niri.action:toggle_window_floating() end

---Move focused window to floating layer
function niri.action:move_window_to_floating() end

---Move focused window to tiling layer
function niri.action:move_window_to_tiling() end

---Focus floating layer
function niri.action:focus_floating() end

---Focus tiling layer
function niri.action:focus_tiling() end

---Switch focus between floating and tiling layers
function niri.action:switch_focus_between_floating_and_tiling() end

---Move floating window by offset
---@param x PositionChange X offset
---@param y PositionChange Y offset
function niri.action:move_floating_window(x, y) end

---Toggle opacity rule for focused window
function niri.action:toggle_window_rule_opacity() end

---Set dynamic cast target to window
---@param window_id? integer? Window ID or nil for focused
function niri.action:set_dynamic_cast_window(window_id) end

---Set dynamic cast target to monitor
---@param monitor? string? Monitor name or nil for focused
function niri.action:set_dynamic_cast_monitor(monitor) end

---Clear dynamic cast target
function niri.action:clear_dynamic_cast_target() end

---Toggle overview mode
function niri.action:toggle_overview() end

---Open overview mode
function niri.action:open_overview() end

---Close overview mode
function niri.action:close_overview() end

---Toggle urgent state of focused window
function niri.action:toggle_window_urgent() end

---Set focused window as urgent
function niri.action:set_window_urgent() end

---Clear urgent state of focused window
function niri.action:unset_window_urgent() end

---Runtime state queries for windows, workspaces, and outputs
---@class niri.state
niri.state = {}

---Get all windows
---@return Window[] # Array of window information
function niri.state.windows() end

---Get the currently focused window
---@return Window? # Focused window or nil
function niri.state.focused_window() end

---Get all workspaces
---@return Workspace[] # Array of workspace information
function niri.state.workspaces() end

---Get all outputs/monitors with position, scale, and transform info
---@return Output[] # Array of output information
function niri.state.outputs() end

---Get keyboard layout information
---@return KeyboardLayouts # Keyboard layout names and current index
function niri.state.keyboard_layouts() end

---Get current cursor position and output
---@return CursorPosition? # Cursor position {x, y, output} or nil if no cursor
function niri.state.cursor_position() end

---Get reserved (exclusive) space for an output from layer-shell surfaces
---@param output_name string Output name to query
---@return ReservedSpace? # Reserved space {top, bottom, left, right} or nil if output not found
function niri.state.reserved_space(output_name) end

---Get current focus mode (normal, overview, layer_shell, or locked)
---@return FocusMode # Current focus mode string
function niri.state.focus_mode() end

---Event loop and timer functionality
---@class niri.loop
niri.loop = {}

---Create a new timer
---@return Timer # New timer instance
function niri.loop.new_timer() end

---Get current time in milliseconds since compositor start
---@return integer # Milliseconds since start
function niri.loop.now() end

---Keybinding configuration
---@class niri.keymap
niri.keymap = {}

---Set a keybinding
---@param mode string Binding mode (e.g., 'normal')
---@param key string Key combination (e.g., 'Mod+Return')
---@param callback fun() Callback function
function niri.keymap.set(mode, key, callback) end

---Window rules configuration
---@class niri.window
niri.window = {}

---Define a window rule
---@param rule table Window rule definition
function niri.window.rule(rule) end

---Overview mode configuration
---@class niri.overview
---@field backdrop_color string? Backdrop color in hex format
niri.overview = {}

---Screenshot configuration
---@class niri.screenshot
---@field path string? Screenshot save path
niri.screenshot = {}

---Operating system utilities for conditional configuration
---@class niri.os
niri.os = {}

---Get the system hostname. Throws on invalid UTF-8 (rare); returns empty string on other system errors.
---@return string # System hostname
function niri.os.hostname() end

---Get the value of an environment variable. Returns nil if not set, empty string if set to empty.
---@param name string Environment variable name
---@return string? # Variable value or nil if not set
function niri.os.getenv(name) end

---Get the current username. Returns nil if unavailable.
---@return string? # Current username or nil
function niri.os.username() end

---Get the user's home directory path. Returns nil if unavailable.
---@return string? # Home directory path or nil
function niri.os.home() end

---Get the system temporary directory path.
---@return string # Temporary directory path
function niri.os.tmpdir() end

---Get the operating system name (e.g., 'linux', 'macos', 'windows').
---@return string # Operating system name
function niri.os.platform() end

---Get the CPU architecture (e.g., 'x86_64', 'aarch64').
---@return string # CPU architecture
function niri.os.arch() end

---Get XDG_CONFIG_HOME (~/.config by default).
---@return string # Config home directory path
function niri.os.xdg_config_home() end

---Get XDG_DATA_HOME (~/.local/share by default).
---@return string # Data home directory path
function niri.os.xdg_data_home() end

---Get XDG_CACHE_HOME (~/.cache by default).
---@return string # Cache home directory path
function niri.os.xdg_cache_home() end

---Get XDG_STATE_HOME (~/.local/state by default).
---@return string # State home directory path
function niri.os.xdg_state_home() end

---Get XDG_RUNTIME_DIR. Returns nil if not set (uncommon on modern systems).
---@return string? # Runtime directory path or nil
function niri.os.xdg_runtime_dir() end

---Get XDG_DATA_DIRS as an array of paths (/usr/local/share:/usr/share by default).
---@return string[] # Array of data directory paths
function niri.os.xdg_data_dirs() end

---Get XDG_CONFIG_DIRS as an array of paths (/etc/xdg by default).
---@return string[] # Array of config directory paths
function niri.os.xdg_config_dirs() end

---Get the niri config directory ($XDG_CONFIG_HOME/niri). Creates if needed.
---@return string # Path to niri config directory
function niri.os.niri_config_dir() end

---Get the niri data directory ($XDG_DATA_HOME/niri). Creates if needed.
---@return string # Path to niri data directory
function niri.os.niri_data_dir() end

---Get the niri cache directory ($XDG_CACHE_HOME/niri). Creates if needed.
---@return string # Path to niri cache directory
function niri.os.niri_cache_dir() end

---Get the niri state directory ($XDG_STATE_HOME/niri). Creates if needed.
---@return string # Path to niri state directory
function niri.os.niri_state_dir() end

---Set or remove an environment variable. Pass nil as value to remove. Changes only affect current process and children.
---@param name string Environment variable name
---@param value? string? Value to set, or nil to remove the variable
function niri.os.setenv(name, value) end

---Filesystem utilities for conditional configuration
---@class niri.fs
niri.fs = {}

---Check if a file exists and is readable. Follows symlinks; broken symlinks return false. Never throws.
---@param path string Path to check
---@return boolean # True if file exists and is readable
function niri.fs.readable(path) end

---Expand ~, $VAR, and ${VAR} in paths. Unset variables expand to empty string. Never throws.
---@param path string Path with variables to expand
---@return string # Expanded path
function niri.fs.expand(path) end

---Find an executable in PATH. Returns full path or nil if not found. Never throws.
---@param command string Command name to find
---@return string? # Full path to executable or nil
function niri.fs.which(command) end

---Check if a path exists (file, directory, or symlink). Never throws.
---@param path string Path to check
---@return boolean # True if path exists
function niri.fs.exists(path) end

---Check if path is a regular file. Follows symlinks. Never throws.
---@param path string Path to check
---@return boolean # True if path is a regular file
function niri.fs.is_file(path) end

---Check if path is a directory. Follows symlinks. Never throws.
---@param path string Path to check
---@return boolean # True if path is a directory
function niri.fs.is_dir(path) end

---Check if path is a symbolic link. Does not follow the link. Never throws.
---@param path string Path to check
---@return boolean # True if path is a symlink
function niri.fs.is_symlink(path) end

---Check if path exists and has executable permission. Follows symlinks. Never throws.
---@param path string Path to check
---@return boolean # True if path is executable
function niri.fs.is_executable(path) end

---Get the filename component of a path. Pure string operation.
---@param path string Path to extract basename from
---@return string # Filename component
function niri.fs.basename(path) end

---Get the directory component of a path. Pure string operation.
---@param path string Path to extract dirname from
---@return string # Directory component
function niri.fs.dirname(path) end

---Get the file extension including the dot. Returns empty string if no extension.
---@param path string Path to extract extension from
---@return string # File extension (e.g., '.txt') or empty string
function niri.fs.extname(path) end

---Join path components intelligently. Handles separators and absolute paths.
---@param ... string Path components to join
---@return string # Joined path
function niri.fs.joinpath(...) end

---List all entries in a directory. Returns sorted basenames. Returns nil, error on failure.
---@param dir string Directory path
---@return string[]|nil # Array of entry names or nil on error
function niri.fs.list(dir) end

---List files only in a directory. Optional Lua pattern filters filenames. Returns sorted basenames.
---@param dir string Directory path
---@param pattern? string? Optional Lua pattern to filter filenames
---@return string[]|nil # Array of filenames or nil on error
function niri.fs.list_files(dir, pattern) end

---List directories only in a directory. Returns sorted basenames.
---@param dir string Directory path
---@return string[]|nil # Array of directory names or nil on error
function niri.fs.list_dirs(dir) end

---Create a directory. Pass true or {recursive=true} for recursive creation.
---@param path string Directory path to create
---@param opts? boolean|table? Options: true or {recursive=true} for recursive creation
---@return boolean # True on success, nil and error message on failure
function niri.fs.mkdir(path, opts) end

---Remove an empty directory. Returns nil, error if not empty or on failure.
---@param path string Directory path to remove
---@return boolean # True on success, nil and error message on failure
function niri.fs.rmdir(path) end

---Remove a file or directory. Pass {recursive=true} for recursive removal.
---@param path string Path to remove
---@param opts? table? Options: {recursive=true} for recursive removal
---@return boolean # True on success, nil and error message on failure
function niri.fs.remove(path, opts) end

---Get absolute path, resolving . and .. and expanding ~/$$VAR. Returns nil, error if path doesn't exist.
---@param path string Path to resolve
---@return string|nil # Absolute path or nil if not found
function niri.fs.abspath(path) end

---Normalize a path by expanding ~/$$VAR and resolving . and .. without requiring existence.
---@param path string Path to normalize
---@return string # Normalized path
function niri.fs.normalize(path) end

---Read entire file as UTF-8 string. Expands ~ in path. Returns nil, error on failure.
---@param path string Path to file to read
---@return string? # File contents or nil on error
---@return string? # Error message or nil on success
function niri.fs.read(path) end

---Read file and return lines as array (without newlines). Expands ~ in path. Returns nil, error on failure.
---@param path string Path to file to read
---@return string[]? # Array of lines or nil on error
---@return string? # Error message or nil on success
function niri.fs.readlines(path) end

---Write content to file, creating or overwriting. Expands ~ in path. Does not auto-create parent directories.
---@param path string Path to file to write
---@param content string Content to write
---@return boolean # True on success, false on error
---@return string? # Error message or nil on success
function niri.fs.write(path, content) end

---Append content to file, creating if it doesn't exist. Expands ~ in path. Does not auto-create parent directories.
---@param path string Path to file to append to
---@param content string Content to append
---@return boolean # True on success, false on error
---@return string? # Error message or nil on success
function niri.fs.append(path, content) end

---Copy a file from src to dst. Only copies files (not directories). Expands ~ in both paths. Overwrites dst if exists.
---@param src string Source file path
---@param dst string Destination file path
---@return boolean # True on success, false on error
---@return string? # Error message or nil on success
function niri.fs.copy(src, dst) end

---Rename/move a file or directory. Expands ~ in both paths. May overwrite dst depending on OS.
---@param src string Source path
---@param dst string Destination path
---@return boolean # True on success, false on error
---@return string? # Error message or nil on success
function niri.fs.rename(src, dst) end

---Get file/directory metadata. Follows symlinks. Returns table with size, mtime, atime, ctime, mode (unix), type, readonly.
---@param path string Path to stat
---@return table? # Metadata table or nil on error
---@return string? # Error message or nil on success
function niri.fs.stat(path) end

---Get file modification time as Unix timestamp. Expands ~ in path.
---@param path string Path to check
---@return integer? # Unix timestamp or nil on error
---@return string? # Error message or nil on success
function niri.fs.mtime(path) end

---Get file size in bytes. Expands ~ in path.
---@param path string Path to check
---@return integer? # Size in bytes or nil on error
---@return string? # Error message or nil on success
function niri.fs.size(path) end

---Find files matching a shell-style glob pattern. Expands ~ in pattern. Supports *, ?, [abc], [!abc], and ** for recursive matching. Returns sorted array of normalized full paths.
---@param pattern string Glob pattern (e.g., '*.lua', 'src/**/*.rs', '~/config/*.conf')
---@return string[]? # Array of matching paths or nil on error
---@return string? # Error message or nil on success
function niri.fs.glob(pattern) end

---Find files/directories by name with upward or downward search. Upward search walks toward root (useful for finding project markers like .git). Downward search recurses into subdirectories. Supports simple glob patterns (* and ?) in names for downward search.
---@param names string|string[] Filename(s) to find. Can include * and ? wildcards for downward search.
---@param opts? FsFindOpts? Search options: path (starting directory, default: cwd), upward (search toward root, default: false), stop (stop upward search at this directory), type ('file' or 'directory' filter), limit (max results)
---@return string[]? # Array of matching paths (sorted) or nil on error
---@return string? # Error message or nil on success
function niri.fs.find(names, opts) end

