---@meta
-- THIS FILE IS AUTO-GENERATED BY build.rs - DO NOT EDIT
-- Regenerate by running: cargo build -p niri-lua
--
-- Niri Lua API Type Definitions
-- For use with EmmyLua-compatible LSP servers

-- ============================================================================
-- Type Aliases
-- ============================================================================

---Window information table
---@alias Window { id: integer, title: string?, app_id: string?, workspace_id: integer?, is_focused: boolean, is_floating: boolean }

---Workspace information table
---@alias Workspace { id: integer, idx: integer, name: string?, output: string?, is_active: boolean, is_focused: boolean, active_window_id: integer? }

---Output/monitor information table
---@alias Output { name: string, make: string?, model: string?, serial: string?, physical_size: { width: integer, height: integer }?, current_mode: { width: integer, height: integer, refresh: integer }?, vrr_supported: boolean, vrr_enabled: boolean }

---Size change value: integer for absolute, '+N'/'-N' for relative, 'N%' for percentage
---@alias SizeChange integer|string

---Position change value: integer for absolute, '+N'/'-N' for relative
---@alias PositionChange integer|string

---Layout switch target: 'next', 'prev', or layout name
---@alias LayoutSwitchTarget "next"|"prev"|string

---Workspace reference: index, name, or table with id/name/index
---@alias WorkspaceReference integer|string|{ id: integer }|{ name: string }|{ index: integer }

-- ============================================================================
-- UserData Types
-- ============================================================================

---A timer for scheduling callbacks
---@class Timer
---@field id integer Unique timer identifier
local Timer = {}

---Start the timer with a delay and optional repeat interval
---@param delay_ms integer Delay in milliseconds before first callback
---@param repeat_ms? integer Repeat interval in milliseconds (0 for one-shot)
---@param callback fun() Callback function
---@return Timer # Self for chaining
function Timer:start(delay_ms, repeat_ms, callback) end

---Stop the timer without closing it
---@return Timer # Self for chaining
function Timer:stop() end

---Stop and close the timer, releasing resources
function Timer:close() end

---Check if the timer is currently active
---@return boolean # True if timer is active
function Timer:is_active() end

---Animation configuration
---@class Animation
---@field name string Animation name
---@field duration_ms integer Duration in milliseconds
---@field curve string Easing curve
local Animation = {}

---Get the animation name
---@return string
function Animation:get_name() end

---Get the duration in milliseconds
---@return integer
function Animation:get_duration() end

---Get the easing curve
---@return string
function Animation:get_curve() end

---Create a copy with different duration
---@param ms integer Duration in milliseconds
---@return Animation # New animation with updated duration
function Animation:with_duration(ms) end

---Create a copy with different easing curve
---@param curve string Easing curve name
---@return Animation # New animation with updated curve
function Animation:with_curve(curve) end

---Window filter for matching windows
---@class Filter
local Filter = {}

---Check if a window matches this filter
---@param app_id string? Application ID
---@param title string? Window title
---@return boolean # True if window matches
function Filter:matches(app_id, title) end

---Get the app_id pattern
---@return string?
function Filter:get_app_id() end

---Get the title pattern
---@return string?
function Filter:get_title() end

---Window rule configuration
---@class WindowRule
local WindowRule = {}

---Check if a window matches this rule
---@param app_id string? Application ID
---@param title string? Window title
---@return boolean # True if window matches
function WindowRule:matches(app_id, title) end

---Get floating setting
---@return boolean?
function WindowRule:get_floating() end

---Get fullscreen setting
---@return boolean?
function WindowRule:get_fullscreen() end

---Create a copy with floating setting
---@param floating boolean Floating state
---@return WindowRule # New rule with updated setting
function WindowRule:with_floating(floating) end

---Create a copy with fullscreen setting
---@param fullscreen boolean Fullscreen state
---@return WindowRule # New rule with updated setting
function WindowRule:with_fullscreen(fullscreen) end

-- ============================================================================
-- Modules
-- ============================================================================

---Root niri namespace providing access to compositor functionality
---@class niri
---@field utils niri_utils Utility functions
---@field config niri_config Configuration API
---@field action niri_action Compositor actions
---@field state niri_state Runtime state queries
---@field loop niri_loop Event loop and timers
---@field keymap niri_keymap Keybinding configuration
niri = {}

---Returns the niri version string
---@return string # niri version
function niri.version() end

---Print values to the niri log (info level)
---@param ... any Values to print
function niri.print(...) end

---Apply configuration from a Lua table
---@param config table Configuration table
function niri.apply_config(config) end

---Utility functions for logging and process spawning
---@class niri_utils
local niri_utils = {}

---Log a message at info level
---@param ... any Values to log
function niri_utils.log(...) end

---Log a message at debug level
---@param ... any Values to log
function niri_utils.debug(...) end

---Log a message at warning level
---@param ... any Values to log
function niri_utils.warn(...) end

---Log a message at error level
---@param ... any Values to log
function niri_utils.error(...) end

---Spawn a command asynchronously
---@param command string[] Command and arguments
function niri_utils.spawn(command) end

---Configuration version and metadata
---@class niri_config
local niri_config = {}

---Returns the config API version
---@return string # Config API version
function niri_config.version() end

---Keybinding configuration
---@class niri_keymap
local niri_keymap = {}

---Set a keybinding
---@param mode string Binding mode (e.g., 'normal')
---@param key string Key combination (e.g., 'Mod+Return')
---@param callback fun() Callback function
function niri_keymap.set(mode, key, callback) end

---Runtime state queries for windows, workspaces, and outputs
---@class niri_state
local niri_state = {}

---Get all windows
---@return Window[] # Array of window information
function niri_state.windows() end

---Get the currently focused window
---@return Window? # Focused window or nil
function niri_state.focused_window() end

---Get all workspaces
---@return Workspace[] # Array of workspace information
function niri_state.workspaces() end

---Get all outputs/monitors
---@return Output[] # Array of output information
function niri_state.outputs() end

---Event loop and timer functionality
---@class niri_loop
local niri_loop = {}

---Create a new timer
---@return Timer # New timer instance
function niri_loop.new_timer() end

---Get current time in milliseconds since compositor start
---@return integer # Milliseconds since start
function niri_loop.now() end

---Compositor actions for window management, navigation, and system control
---@class niri_action
local niri_action = {}

-- === System ===

---Quit the compositor
---@param skip_confirmation? boolean Skip confirmation dialog
function niri_action:quit(skip_confirmation) end

---Turn off all monitors
function niri_action:power_off_monitors() end

---Turn on all monitors
function niri_action:power_on_monitors() end

---Spawn a command
---@param command string[] Command and arguments
function niri_action:spawn(command) end

---Spawn a command via shell
---@param command string Shell command string
function niri_action:spawn_sh(command) end

---Trigger a screen transition animation
---@param delay? boolean Whether to delay
function niri_action:do_screen_transition(delay) end

---Reload configuration from file
function niri_action:load_config_file() end

-- === Screenshot ===

---Take a screenshot (interactive selection)
function niri_action:screenshot() end

---Screenshot the entire screen
function niri_action:screenshot_screen() end

---Screenshot the focused window
function niri_action:screenshot_window() end

-- === Window ===

---Close the focused window
function niri_action:close_window() end

---Toggle fullscreen on the focused window
function niri_action:fullscreen_window() end

---Toggle windowed fullscreen mode
function niri_action:toggle_windowed_fullscreen() end

---Focus a specific window by ID
---@param window_id integer Window ID
function niri_action:focus_window(window_id) end

---Focus the previously focused window
function niri_action:focus_window_previous() end

---Toggle keyboard shortcuts inhibit
function niri_action:toggle_keyboard_shortcuts_inhibit() end

-- === Column Focus ===

---Focus the column to the left
function niri_action:focus_column_left() end

---Focus the column to the right
function niri_action:focus_column_right() end

---Focus the first column
function niri_action:focus_column_first() end

---Focus the last column
function niri_action:focus_column_last() end

---Focus column right, wrapping to first
function niri_action:focus_column_right_or_first() end

---Focus column left, wrapping to last
function niri_action:focus_column_left_or_last() end

---Focus column by index
---@param index integer 1-based column index
function niri_action:focus_column(index) end

-- === Window Focus ===

---Focus the window below in the column
function niri_action:focus_window_down() end

---Focus the window above in the column
function niri_action:focus_window_up() end

---Focus window by index in focused column
---@param index integer 1-based index from top
function niri_action:focus_window_in_column(index) end

---Focus window above or monitor above
function niri_action:focus_window_or_monitor_up() end

---Focus window below or monitor below
function niri_action:focus_window_or_monitor_down() end

---Focus column left or monitor left
function niri_action:focus_column_or_monitor_left() end

---Focus column right or monitor right
function niri_action:focus_column_or_monitor_right() end

---Focus window below or column to the left
function niri_action:focus_window_down_or_column_left() end

---Focus window below or column to the right
function niri_action:focus_window_down_or_column_right() end

---Focus window above or column to the left
function niri_action:focus_window_up_or_column_left() end

---Focus window above or column to the right
function niri_action:focus_window_up_or_column_right() end

---Focus window below or workspace below
function niri_action:focus_window_or_workspace_down() end

---Focus window above or workspace above
function niri_action:focus_window_or_workspace_up() end

---Focus the topmost window in column
function niri_action:focus_window_top() end

---Focus the bottommost window in column
function niri_action:focus_window_bottom() end

---Focus window below or wrap to top
function niri_action:focus_window_down_or_top() end

---Focus window above or wrap to bottom
function niri_action:focus_window_up_or_bottom() end

-- === Column Move ===

---Move column to the left
function niri_action:move_column_left() end

---Move column to the right
function niri_action:move_column_right() end

---Move column to first position
function niri_action:move_column_to_first() end

---Move column to last position
function niri_action:move_column_to_last() end

---Move column left or to monitor left
function niri_action:move_column_left_or_to_monitor_left() end

---Move column right or to monitor right
function niri_action:move_column_right_or_to_monitor_right() end

---Move column to specific index
---@param index integer 1-based target index
function niri_action:move_column_to_index(index) end

-- === Window Move ===

---Move window down within column
function niri_action:move_window_down() end

---Move window up within column
function niri_action:move_window_up() end

---Move window down or to workspace below
function niri_action:move_window_down_or_to_workspace_down() end

---Move window up or to workspace above
function niri_action:move_window_up_or_to_workspace_up() end

---Swap focused window with window to the left
function niri_action:swap_window_left() end

---Swap focused window with window to the right
function niri_action:swap_window_right() end

-- === Consume/Expel ===

---Consume window from left or expel to left
function niri_action:consume_or_expel_window_left() end

---Consume window from right or expel to right
function niri_action:consume_or_expel_window_right() end

---Consume adjacent window into current column
function niri_action:consume_window_into_column() end

---Expel focused window from column
function niri_action:expel_window_from_column() end

-- === Column Display ===

---Toggle tabbed display for column
function niri_action:toggle_column_tabbed_display() end

---Set column display mode
---@param display "normal"|"tabbed" Display mode
function niri_action:set_column_display(display) end

---Center the current column on screen
function niri_action:center_column() end

---Center the focused window on screen
function niri_action:center_window() end

---Center all fully visible columns
function niri_action:center_visible_columns() end

-- === Workspace ===

---Focus the workspace below
function niri_action:focus_workspace_down() end

---Focus the workspace above
function niri_action:focus_workspace_up() end

---Focus a specific workspace
---@param reference WorkspaceReference Workspace to focus
function niri_action:focus_workspace(reference) end

---Focus the previously active workspace
function niri_action:focus_workspace_previous() end

---Move window to workspace below
function niri_action:move_window_to_workspace_down() end

---Move window to workspace above
function niri_action:move_window_to_workspace_up() end

---Move window to specific workspace
---@param reference WorkspaceReference Target workspace
function niri_action:move_window_to_workspace(reference) end

---Move column to workspace below
function niri_action:move_column_to_workspace_down() end

---Move column to workspace above
function niri_action:move_column_to_workspace_up() end

---Move column to specific workspace
---@param reference WorkspaceReference Target workspace
function niri_action:move_column_to_workspace(reference) end

---Move current workspace down
function niri_action:move_workspace_down() end

---Move current workspace up
function niri_action:move_workspace_up() end

---Move workspace to specific index
---@param index integer Target index
function niri_action:move_workspace_to_index(index) end

---Set the name of a workspace
---@param name string New workspace name
function niri_action:set_workspace_name(name) end

---Unset the name of a workspace
function niri_action:unset_workspace_name() end

-- === Workspace to Monitor ===

---Move workspace to monitor on the left
function niri_action:move_workspace_to_monitor_left() end

---Move workspace to monitor on the right
function niri_action:move_workspace_to_monitor_right() end

---Move workspace to monitor below
function niri_action:move_workspace_to_monitor_down() end

---Move workspace to monitor above
function niri_action:move_workspace_to_monitor_up() end

---Move workspace to previously active monitor
function niri_action:move_workspace_to_monitor_previous() end

---Move workspace to next monitor
function niri_action:move_workspace_to_monitor_next() end

---Move workspace to specific monitor
---@param output string Target output name
function niri_action:move_workspace_to_monitor(output) end

-- === Monitor Focus ===

---Focus monitor to the left
function niri_action:focus_monitor_left() end

---Focus monitor to the right
function niri_action:focus_monitor_right() end

---Focus monitor below
function niri_action:focus_monitor_down() end

---Focus monitor above
function niri_action:focus_monitor_up() end

---Focus previously active monitor
function niri_action:focus_monitor_previous() end

---Focus next monitor in order
function niri_action:focus_monitor_next() end

---Focus monitor by name
---@param output string Output name
function niri_action:focus_monitor(output) end

-- === Window to Monitor ===

---Move window to monitor on the left
function niri_action:move_window_to_monitor_left() end

---Move window to monitor on the right
function niri_action:move_window_to_monitor_right() end

---Move window to monitor below
function niri_action:move_window_to_monitor_down() end

---Move window to monitor above
function niri_action:move_window_to_monitor_up() end

---Move window to next monitor
function niri_action:move_window_to_monitor_next() end

---Move window to previously active monitor
function niri_action:move_window_to_monitor_previous() end

---Move window to specific monitor
---@param output string Target output name
function niri_action:move_window_to_monitor(output) end

-- === Column to Monitor ===

---Move column to monitor on the left
function niri_action:move_column_to_monitor_left() end

---Move column to monitor on the right
function niri_action:move_column_to_monitor_right() end

---Move column to monitor below
function niri_action:move_column_to_monitor_down() end

---Move column to monitor above
function niri_action:move_column_to_monitor_up() end

---Move column to next monitor
function niri_action:move_column_to_monitor_next() end

---Move column to previously active monitor
function niri_action:move_column_to_monitor_previous() end

---Move column to specific monitor
---@param output string Target output name
function niri_action:move_column_to_monitor(output) end

-- === Size/Width/Height ===

---Set the window width
---@param change SizeChange Width change value
function niri_action:set_window_width(change) end

---Set the window height
---@param change SizeChange Height change value
function niri_action:set_window_height(change) end

---Reset window height to default
function niri_action:reset_window_height() end

---Switch to next preset column width
function niri_action:switch_preset_column_width() end

---Switch to previous preset column width
function niri_action:switch_preset_column_width_back() end

---Switch to next preset window width
function niri_action:switch_preset_window_width() end

---Switch to previous preset window width
function niri_action:switch_preset_window_width_back() end

---Switch to next preset window height
function niri_action:switch_preset_window_height() end

---Switch to previous preset window height
function niri_action:switch_preset_window_height_back() end

---Maximize column to fill workspace
function niri_action:maximize_column() end

---Toggle maximize window to edges
function niri_action:maximize_window_to_edges() end

---Set column width
---@param change SizeChange Width change value
function niri_action:set_column_width(change) end

---Expand column to fill available width
function niri_action:expand_column_to_available_width() end

-- === Layout ===

---Switch keyboard layout
---@param target LayoutSwitchTarget Layout to switch to
function niri_action:switch_layout(target) end

---Show the hotkey overlay
function niri_action:show_hotkey_overlay() end

-- === Debug ===

---Toggle debug tint visualization
function niri_action:toggle_debug_tint() end

---Toggle opaque regions debug
function niri_action:debug_toggle_opaque_regions() end

---Toggle damage debug visualization
function niri_action:debug_toggle_damage() end

-- === Floating ===

---Toggle floating state of focused window
function niri_action:toggle_window_floating() end

---Move focused window to floating layer
function niri_action:move_window_to_floating() end

---Move focused window to tiling layer
function niri_action:move_window_to_tiling() end

---Focus floating layer
function niri_action:focus_floating() end

---Focus tiling layer
function niri_action:focus_tiling() end

---Switch focus between layers
function niri_action:switch_focus_between_floating_and_tiling() end

---Move floating window by offset
---@param x PositionChange X position change
---@param y PositionChange Y position change
function niri_action:move_floating_window(x, y) end

-- === Overview ===

---Toggle overview mode
function niri_action:toggle_overview() end

---Open overview mode
function niri_action:open_overview() end

---Close overview mode
function niri_action:close_overview() end

-- === Window Rules / Misc ===

---Toggle window rule opacity for focused window
function niri_action:toggle_window_rule_opacity() end

---Toggle urgent status of a window
---@param id integer Window ID
function niri_action:toggle_window_urgent(id) end

---Set urgent status of a window
---@param id integer Window ID
function niri_action:set_window_urgent(id) end

---Unset urgent status of a window
---@param id integer Window ID
function niri_action:unset_window_urgent(id) end

---Set dynamic cast target to a window
function niri_action:set_dynamic_cast_window() end

---Set dynamic cast target to a monitor
---@param output? string Output name (optional)
function niri_action:set_dynamic_cast_monitor(output) end

---Clear dynamic cast target
function niri_action:clear_dynamic_cast_target() end

